version: "2"

services:
  hycloud-site:
    build: .
    container_name: hycloud-site
    ports:
      - "3480:80"
    networks:
      - hycloud-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    mem_limit: 256m
    cpu_shares: 512
    restart: unless-stopped

networks:
  hycloud-network:
    driver: bridge
