version: "2"

services:
  hycloud-site:
    build: .
    container_name: hycloud-site
    expose:
      - "80"
    networks:
      - proxy-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    mem_limit: 256m
    cpu_shares: 512
    restart: unless-stopped

networks:
  proxy-network:
    external: true
